# Generated by Django 3.0 on 2021-06-19 19:44

from django.db import migrations, models
import imdbapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Related Org to associate with', max_length=255, null=True)),
                ('director', models.CharField(blank=True, help_text='Related Org to associate with', max_length=255, null=True)),
                ('imdb_score', models.FloatField(blank=True, help_text='Related Org to associate with', null=True, validators=[imdbapp.models.imdb_score_validation])),
                ('popularity', models.FloatField(blank=True, help_text='Related Org to associate with', null=True, validators=[imdbapp.models.popularity_validation])),
                ('create_date', models.DateTimeField(blank=True, help_text='Related Org to associate with', null=True)),
                ('edit_date', models.DateTimeField(blank=True, help_text='Related Org to associate with', null=True)),
                ('genre', models.ManyToManyField(blank=True, help_text='Related Org to associate with', max_length=255, null=True, to='imdbapp.Genre')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ('id',),
            },
        ),
    ]
